//! Local IPC between the DeskSync background service and its clients.
//!
//! Once the agent runs as a background service, nothing can ask it how it is
//! doing: the terminal that started it is gone. This crate is the answer — a
//! small request/response channel the service listens on and the CLI (`status`)
//! or the configuration UI connects to.
//!
//! Shape of the channel:
//! - **Transport**: a Unix domain socket in the agent's config directory. Only
//!   the owning user can reach it, because the directory is owner-only.
//! - **Framing**: one JSON value per line. Trivially debuggable with `nc`, and
//!   line framing is enough because every message is small and self-contained.
//! - **Auth**: a per-install token, generated by the service and stored
//!   owner-only next to the socket. Filesystem permissions are the real security
//!   boundary; the token is defence in depth for a mistakenly-widened directory,
//!   and it is compared in constant time.
//!
//! Windows named pipes are not implemented yet: [`server::listen`] and
//! [`client::request`] return [`IpcError::Unsupported`] there rather than
//! pretending to work.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

pub mod client;
pub mod protocol;
pub mod server;

pub use client::request;
pub use protocol::{
    CaptureStatus, Envelope, IpcError, Request, Response, ServiceStatus, StatusSource, PROTOCOL_VERSION,
};
pub use server::{listen, socket_path, token_path, IpcServer};
