{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "desksync.serviceAccountName" . }}
  labels:
    {{- include "desksync.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# Services make no calls to the Kubernetes API, so no token is mounted.
automountServiceAccountToken: false
{{- end }}
