{{- $ := . -}}
{{- range $name, $svc := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- include "desksync.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
spec:
  type: {{ $svc.serviceType | default "ClusterIP" }}
  selector:
    {{- include "desksync.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - name: http
      port: {{ $svc.port }}
      targetPort: http
      protocol: TCP
{{- end }}
